source 'https://rubygems.org'

gem 'berkshelf'
gem 'hashie'
gem 'chefspec'
gem 'test-kitchen', '~> 1.4.2'
gem 'kitchen-vagrant'
gem 'kitchen-docker'
gem 'kitchen-transport-rsync'
gem 'kitchen-ec2'
gem 'foodcritic'
gem 'winrm-transport'
